"""
LLM explanation layer (Groq). Sits strictly AFTER the numeric pipeline.

Input : the assessment dict produced by assess.AssessmentService (predictions, percentiles,
        intervals, SHAP contributions, confidence tiers, stress score).
Output: plain-language summary, interpretation, ranked actions, caveats — text only.

The model never generates or modifies predictions, intervals, percentiles, SHAP values or the
score. `render_context()` serialises the numbers into the prompt; `explain()` validates the
reply as JSON and returns it alongside the untouched assessment. Any failure (no API key,
network, malformed reply) yields None plus an error string; the dashboard still renders the
numeric assessment.
"""

from __future__ import annotations

import json
import logging
import os
from datetime import datetime, timezone

log = logging.getLogger(__name__)

DEFAULT_MODEL = "llama-3.3-70b-versatile"
DISCLAIMER = ("Generated by a language model from the numeric assessment above. It does not add "
              "measurements or predictions; verify against the indicator values and intervals.")

SYSTEM_PROMPT = """You are the explanation layer of HydroSentinel, a satellite-based freshwater condition assessment tool.
You receive a structured assessment for ONE Sentinel-2 observation at ONE location: predicted turbidity,
chlorophyll-a and CDOM (fDOM proxy), each with a 90% conformal prediction interval, a percentile relative to
the site's or basin's own historical observations, a status, a confidence tier, and its top SHAP contributions.
A composite Freshwater Stress Score (0-100, equal-weight mean of the available percentiles) is included.

Your job: explain, interpret, and suggest ranked actions for a water manager. You must:
- Use ONLY the numbers given. Never invent, round differently, or "correct" any value.
- Describe the score as an anomaly indicator relative to the site's own history, NOT a validated ecological health index.
- Phrase SHAP items as contributions to the model's prediction ("contributed to", "pushed the prediction up"), never as causes.
- Phrase indicators carefully: "predicted chlorophyll-a is unusually high relative to this site's record", not "the ecosystem is unhealthy".
- Respect the confidence tier: Low / Very low confidence and out-of-region tiers must be stated prominently and actions must be cautious (verify first).
- Never forecast the future or mention days ahead. This is a current-condition estimate only.
- Keep it concise and concrete. No marketing language.

Respond with a single JSON object:
{
  "summary": "2-3 sentences: what the assessment says, in plain language",
  "interpretation": "1 short paragraph: which indicators drive the score, what the intervals and confidence mean, what the SHAP contributions suggest about the satellite signal",
  "actions": [ {"rank": 1, "action": "...", "rationale": "..."}, ... up to 4, most useful first ],
  "caveats": ["...", "..."]
}"""


def render_context(a: dict) -> str:
    """Compact, numeric, unambiguous serialisation of the assessment for the prompt."""
    o, s = a["observation"], a["stress"]
    lines = [
        f"LOCATION: {o.get('station_nm') or 'unnamed'} (site {o.get('site_no') or 'n/a'}, basin {o.get('basin') or 'unknown'})",
        f"OBSERVATION: Sentinel-2 overpass {o.get('scene_datetime_utc')}; valid water pixels in 250 m buffer: {o.get('n_mask')}",
        f"VALIDATION TIER: {a['validation_tier']}",
        f"STRESS SCORE: {s['score']} / 100 -> {s['label']} (indicators used: {', '.join(s['indicators_used']) or 'none'}; "
        f"missing: {', '.join(s['indicators_missing']) or 'none'})",
        "",
    ]
    for k, v in a["indicators"].items():
        iv = v["interval"]
        lines.append(f"INDICATOR {v['label']} [{v['unit']}]:")
        lines.append(f"  predicted {v['prediction']}; 90% interval {iv['lower']}-{iv['upper']}"
                     + (f"; matched sonde reading {v['observed']}" if v.get("observed") is not None else ""))
        if v["percentile"] is not None:
            lines.append(f"  percentile {v['percentile']} vs {v['reference_level']} history (n={v['n_reference']}) -> status {v['status']}")
        else:
            lines.append("  percentile: not available (no site/basin reference)")
        lines.append(f"  confidence {v['confidence']} ({v['validation_tier']})")
        if v.get("note"):
            lines.append(f"  note: {v['note']}")
        for c in v["top_contributions"][:3]:
            lines.append(f"  SHAP: {c['label']} {c['direction']} the prediction (x{c['factor']})")
        lines.append("")
    return "\n".join(lines)


def _client():
    key = os.getenv("GROQ_API_KEY")
    if not key:
        return None
    from groq import Groq  # imported lazily so the API works without the package configured
    return Groq(api_key=key)


def explain(assessment: dict, model: str | None = None, temperature: float = 0.2) -> tuple[dict | None, str | None]:
    """Return (llm_explanation, error). Exactly one of the two is non-None."""
    client = _client()
    if client is None:
        return None, "GROQ_API_KEY not set; explanation layer disabled"
    model = model or os.getenv("GROQ_MODEL", DEFAULT_MODEL)
    try:
        resp = client.chat.completions.create(
            model=model, temperature=temperature, max_tokens=900,
            response_format={"type": "json_object"},
            messages=[{"role": "system", "content": SYSTEM_PROMPT},
                      {"role": "user", "content": render_context(assessment)}],
        )
        raw = resp.choices[0].message.content
        out = json.loads(raw)
        out = _validate(out)
    except Exception as exc:  # noqa: BLE001 — any failure must not break the numeric response
        log.warning("LLM explanation failed: %s", exc)
        return None, f"explanation unavailable: {type(exc).__name__}"
    out.update({"model": model, "generated_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
                "disclaimer": DISCLAIMER})
    return out, None


def _validate(out: dict) -> dict:
    if not isinstance(out, dict):
        raise ValueError("reply is not a JSON object")
    summary = str(out.get("summary", "")).strip()
    interp = str(out.get("interpretation", "")).strip()
    if not summary or not interp:
        raise ValueError("missing summary/interpretation")
    actions = []
    for i, act in enumerate(out.get("actions") or [], start=1):
        if isinstance(act, dict) and act.get("action"):
            actions.append({"rank": int(act.get("rank") or i), "action": str(act["action"]).strip(),
                            "rationale": str(act.get("rationale", "")).strip()})
    actions = sorted(actions, key=lambda x: x["rank"])[:4]
    caveats = [str(c).strip() for c in (out.get("caveats") or []) if str(c).strip()][:5]
    return {"summary": summary, "interpretation": interp, "actions": actions, "caveats": caveats}
